### ISSUE TITLE
Problem with korean word.

### ISSUE THREAD

**Issue by latestk-develop** [G-Research/ahocorasick_rs#51] opened 2023-04-07 07:00 UTC
when using find_matches_as_strings method some korean word raise Exception

ex)
r.find_matches_as_strings("나이키 덩크".casefold())
thread '<unnamed>' panicked at 'byte index 12 is not a char boundary; it is inside '덩' (bytes 10..13) of `나이키 덩크`', src\lib.rs:156:53
Traceback (most recent call last):
  File "C:\miniconda3\envs\django\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
pyo3_runtime.PanicException: byte index 12 is not a char boundary; it is inside '덩' (bytes 10..13) of `나이키 덩크`

덩 and 꺽 etc... 
how can solved ?

**Comment by itamarst** [comment] 2023-04-07 16:17
Hi, can you share the relevant strings you are searching for as well, if possible? Or even better, it would be great if you could include a self-contained Python script reproducing the problem.

**Comment by itamarst** [comment] 2023-04-12 20:11
@latestk-develop Just checking again, could you provide a complete, runnable example of the problem?

**Comment by itamarst** [comment] 2023-04-25 20:23
Seems like potential sources of problem are:

1. Unicode/UTF-8 edge cases. @burntsushi given the Python API only accepts strings, is there some weird Unicode thing going on that might cause this?
2. Bug in `aho-corasick` crate.
3. Bug in the way I identify unicode characters (a thin wrapper around Rust's `char_indices()`, so conceivably a bug there?).

**Comment by itamarst** [comment] 2023-05-01 19:35
@latestk-develop Any chance you can give us a complete reproducer? In particular, it'd be useful to know how you initialized the `AhoCorasick()` object.

**Comment by itamarst** [comment] 2023-09-06 15:39
Going to close this since it's unclear if this is a real issue and no reproducer. Please re-open if you encounter this!

**Closed by itamarst** 2023-09-06 15:39 UTC
